openapi: 3.0.3
info:
  title: Electrokerot Website API
  description:
    컴퓨터부품 (parts) / 견적서 (builds)
  contact:
    email: swimmingpolar@gmail.com
  version: 1.0.0
servers:
  - url: http://localhost:5611/v1
tags:
  - name: parts
    description: Computer component parts
  - name: builds
    description: User created computer build
  - name: posts
  - name: comments
  - name: account
paths:
  /parts/{ids}:
    get:
      tags:
        - parts
      summary: Get parts information of given ids
      operationId: getPartsByIds
      parameters:
        - name: ids
          in: path
          required: true
          schema:
            type: array
            items:
              type: string
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Part'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
  /parts/searchQueries:
    get:
      tags:
        - parts
      summary: Get list of autocompleted queries
      operationId: getPartNamesByQuery
      parameters:
        - name: query
          in: query
          style: form
          explode: true
          required: true
          schema:
            type: object
            properties:
              query:
                type: string
              category:
                $ref: '#/components/schemas/Categories'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        '400':
          $ref: '#/components/responses/BadRequest'
  /parts/search:
    post:
      tags:
        - parts
      summary: Get search results
      operationId: getPartsByFilters
      requestBody:
        $ref: '#/components/requestBodies/PartSearch'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Part'
        '400':
          $ref: '#/components/responses/BadRequest'
  /builds:
    get:
      tags:
        - builds
      summary: Get user's list of builds
      operationId: getBuildById
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Build'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
      security:
        - bearerAuth: []
    post:
      tags:
        - builds
      summary: Create new build
      operationId: createBuild
      responses:
        '200':
          description: Ok
        '401':
          $ref: '#/components/responses/Unauthorized'
      security:
        - bearerAuth: []
  /builds/{id}:
    put:
      tags:
        - builds
      summary: Update build
      operationId: updateBuild
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Ok
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
      security:
        - bearerAuth: []
    delete:
      tags:
        - builds
      summary: Delete build
      operationId: deleteBuild
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 'on success'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
      security:
        - bearerAuth: []
  /login:
    post:
      tags:
        - account
      summary: Login
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
      responses:
        '200':
          description: Ok
          headers:
            Authorization:
              schema:
                type: string
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
  /logout:
    get:
      tags:
        - account
      summary: Logout
      operationId: logout
      responses:
        '200':
          description: Ok
        '401':
          $ref: '#/components/responses/Unauthorized'
      security:
        - bearerAuth: []
  /signup:
    post:
      tags:
        - account
      summary: Create account
      operationId: signup
      requestBody:
        $ref: '#/components/requestBodies/Signup'
      responses:
        '200':
          description: Ok
        '400':
          $ref: '#/components/responses/BadRequest'
        '409':
          $ref: '#/components/responses/Conflict'
  /update:
    put:
      tags:
        - account
      summary: Update account profile
      operationId: updateAccountProfile
      requestBody:
        $ref: '#/components/requestBodies/UpdateAccountProfile'
      responses:
        '200':
          description: Ok
        '400':
          $ref: '#/components/responses/BadRequest'
        '409':
          $ref: '#/components/responses/Conflict'
      security:
        - bearerAuth: []
  /delete:
    delete:
      tags:
        - account
      summary: Delete account
      operationId: deleteAccount
      responses:
        '200':
          description: Ok
        '401':
          $ref: '#/components/responses/Unauthorized'
      security:
        - bearerAuth: []
components:
  schemas:
    Part:
      type: object
      properties:
        _id:
          type: string
          example: ObjectId
        name:
          type: string
        category:
          type: string
        variants:
          type: array
          items:
            # $ref: '#/components/schemas/Part'
            # self-referencing (open api cannot render self referneces)
            # list of variants [Part, Part, ...]
            type: string
            example:
              SelfReferencingPartObjects
        details:
          type: object
          additionalProperties:
            properties:
              type:
                type: string
              value:
                type: string
        vendors:
          type: array
          items:
            type: object
            properties:
              marketType:
                type: string
              vendorsList:
                type: array
                items:
                  type: object
                  properties:
                    vendorName:
                      type: string
                    vendorCode:
                      type: string
                    url:
                      type: string
                      format: uri
        prices:
          type: array
          items:
            type: object
            properties:
              timestamp:
                type: string
                format: date-time
              value:
                type: string
    Build:
      type: object
      properties:
        _id:
          type: string
          example: ObjectId
        owner:
          type: string
          example: ObjectId
        name:
          type: string
        isSelected:
          type: boolean
        parts:
          type: array
          items:
            type: object
            additionalProperties:
              properties:
                category:
                  type: object
                  properties:
                    _id:
                      type: string
                      example: ObjectId
                    count:
                      type: integer
                      minimum: 1
                    filters:
    Categories:
      type: string
      enum:
        - cpu
        - mainboard
        - memory
        - graphics
        - ssd
        - hdd
        - power
        - case
        - cooler
  requestBodies:
    PartSearch:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              category:
                $ref: '#/components/schemas/Categories'
              page:
                type: integer
                minimum: 1
              filter:
                type: object
                properties:
                  searchQuery:
                    type: string
                additionalProperties:
                  type: array
                  items:
                    type: string
            required:
              - category
              - page
    Signup:
      content:
        application/json:
          schema:
            type: object
            properties:
              email:
                type: string
                format: email
              password:
                type: string
                format: password
              passwordConfirm:
                type: string
                format: password
              nickname:
                type: string
    UpdateAccountProfile:
      content:
        application/json:
          schema:
            type: object
            properties:
              password:
                type: string
                format: password
              passwordConfirm:
                type: string
                format: password
              nickname:
                type: string
  responses:
    BuildResponse:
      description: Build information object
      content:
        application/json:
          schema:
            type: object
    BadRequest:
      description: Invalid request
    Unauthorized:
      description: Unauthorized access
    Forbidden:
      description: Request forbidden
    NotFound:
      description: Resource not found
    Conflict:
      description: Resource conflicts
    ServerError:
      description: Internal server error
    ServerBusy:
      description: Server is busy
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT