name: Node.js CI

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ElectroKerotDevelopment
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Set .env file
      env:
        PORT: ${{ secrets.PORT }}
        DATABASE_URI: ${{ secrets.DATABASE_URI }}
        DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
      run: |
        echo "PORT=$PORT" >> .env
        echo "DATABASE_URI=$DATABASE_URI" >> .env
        echo "DATABASE_NAME=$DATABASE_NAME" >> .env
        echo "JWT_SECRET=$JWT_SECRET" >> .env
        
    - name: Step 1
    - run: |
        if [ "${{ secrets.PORT }}" == "5611" ]; then
          echo "Match"
        else
          echo "Not matched"
        fi
    - run: |
        pwd
    - run: |
        ls -al
        
    
#     - uses: actions/checkout@v3
#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v3
#       with:
#         node-version: ${{ matrix.node-version }}
#         cache: 'npm'
#     - run: npm ci
#     - run: npm run build --if-present
#     - run: npm test

